const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={user:null,role:null,view:'dashboard',cache:{}};
const ROLE={
  coordinator:{label:'Coordinator / Administrator',icon:'C',tone:'coordinator'},
  student:{label:'Student',icon:'S',tone:'student'},
  adviser:{label:'Adviser',icon:'A',tone:'adviser'},
  panel_member:{label:'Panel Member',icon:'P',tone:'panel'}
};
const NAV={
  coordinator:[
    ['group','Operations'],['dashboard','Dashboard','⌂'],['requests','Defense Requests','↗'],['schedules','Defense Scheduling','◷'],['panels','Panel Assignment','◇'],['rooms','Rooms','□'],
    ['group','Academic records'],['projects','Projects','▣'],['evaluations','Evaluations','✓'],['reports','Reports','▤'],
    ['group','Administration'],['users','User Management','♙'],['management','Project Plan','▥']
  ],
  student:[
    ['group','My process'],['dashboard','Dashboard','⌂'],['requests','Defense Request','↗'],['schedules','My Schedule','◷'],['projects','My Project','▣'],['panels','Assigned Panel','◇'],['evaluations','Defense Result','✓']
  ],
  adviser:[
    ['group','Advising'],['dashboard','Dashboard','⌂'],['projects','Assigned Students & Projects','▣'],['schedules','Defense Schedule','◷'],['evaluations','Evaluation / Comments','✓']
  ],
  panel_member:[
    ['group','Defense duties'],['dashboard','Dashboard','⌂'],['schedules','Assigned Defenses & Schedule','◷'],['evaluations','Evaluation','✓']
  ]
};
const TITLES={dashboard:['Overview','Dashboard'],requests:['Defense workflow','Defense Requests'],schedules:['Scheduling','Defense Scheduling'],panels:['Assignments','Panel Assignment'],rooms:['Facilities','Rooms'],projects:['Academic records','Projects'],evaluations:['Results','Evaluations'],users:['Administration','User Management'],management:['Project controls','Project Plan'],reports:['Reports','Reports']};

let csrfToken='';
async function api(url,opts={}){
  const method=(opts.method||'GET').toUpperCase();
  if(method!=='GET'&&method!=='HEAD'&&url!=='/api/csrf'&&!csrfToken){ const c=await fetch('/api/csrf',{credentials:'same-origin'}); const cd=await c.json().catch(()=>({})); csrfToken=cd.token||''; }
  const headers={'Content-Type':'application/json',...(opts.headers||{})}; if(method!=='GET'&&method!=='HEAD'&&csrfToken)headers['X-CSRF-Token']=csrfToken;
  const res=await fetch(url,{credentials:'same-origin',...opts,headers});
  const data=await res.json().catch(()=>({}));
  if(!res.ok) throw new Error(data.error||'Request failed.');
  return data;
}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\'':'&#39;','"':'&quot;'}[c]));}
function money(v){return new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:0}).format(Number(v||0));}
function dateParts(v){const s=String(v??'').trim(); const m=s.match(/^(\d{4})-(\d{2})-(\d{2})/); if(!m)return null; const y=Number(m[1]),mo=Number(m[2]),d=Number(m[3]); if(!Number.isInteger(y)||!Number.isInteger(mo)||!Number.isInteger(d)||mo<1||mo>12||d<1||d>31)return null; return {y,mo,d};}
function dateFmt(v){const p=dateParts(v); if(!p)return '—'; const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']; return `${months[p.mo-1]} ${p.d}, ${p.y}`;}
function timeFmt(v){if(!v)return '—'; const s=String(v); const m=s.match(/(?:^|T)(\d{1,2}):(\d{2})/); if(!m)return '—'; const h=Number(m[1]), min=Number(m[2]); if(!Number.isInteger(h)||!Number.isInteger(min)||h<0||h>23||min<0||min>59)return '—'; const d=new Date(2000,0,1,h,min); return d.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'});}
function statusTag(v=''){const cls=v.toLowerCase().replace(/\s+/g,'');const map={'inprogress':'inprogress','notstarted':'planned','resubmitted':'resubmitted','atrisk':'atrisk','returned':'returned','active':'active'};return `<span class="status ${map[cls]||cls}">${esc(v)}</span>`}
function initials(name=''){return name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'?'}
function avatarMarkup(user, cls='user-table-avatar'){
  const name=esc(user?.full_name||'');
  const initial=esc(initials(user?.full_name||''));
  if(!user?.profile_image) return `<span class="${cls}">${initial}</span>`;
  return `<span class="${cls} has-image"><img src="${esc(user.profile_image)}" alt="${name} profile picture" onerror="this.style.display='none';this.nextElementSibling.style.display='grid';"><span class="avatar-fallback" style="display:none">${initial}</span></span>`;
}
function setAvatar(el,user){if(!el)return; el.outerHTML=avatarMarkup(user,el.className||'top-avatar');}
function roleLabel(r){return ROLE[r]?.label||r}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2600)}

function applyRoleTheme(role){ document.body.classList.remove('theme-student','theme-adviser','theme-panel','theme-coordinator'); const tone=ROLE[role]?.tone; if(tone) document.body.classList.add('theme-'+tone); }
function showApp(){
  applyRoleTheme(state.role);
  $('#authRoot').classList.add('hidden');$('#appRoot').classList.remove('hidden');
  $('#identityName').textContent=state.user.full_name;$('#identityRole').textContent=state.user.role_label;
  setAvatar($('#avatar'), state.user);
  renderNav();renderView('dashboard');
}
function renderNav(){
  const nav=$('#nav');nav.innerHTML=(NAV[state.role]||[]).map(item=>item[0]==='group'?`<div class="nav-group">${item[1]}</div>`:`<button class="nav-btn ${state.view===item[0]?'active':''}" data-view="${item[0]}"><span class="nav-icon">${item[2]}</span><span>${item[1]}</span></button>`).join('');
}
function pageHead(kicker,title,desc,actions=''){return `<div class="page-intro"><div><p class="micro">${esc(kicker)}</p><h2>${esc(title)}</h2><p>${esc(desc)}</p></div><div class="actions">${actions}</div></div>`}
function stat(label,value,detail,accent=''){return `<div class="stat-card"><small>${esc(label)}</small><strong class="${accent}">${esc(value)}</strong><em>${esc(detail)}</em></div>`}

async function renderView(view){
  const allowed=(NAV[state.role]||[]).some(x=>x[0]===view);
  if(!allowed) view='dashboard';
  state.view=view;renderNav();
  const t=TITLES[view]||['Workspace','Dashboard'];$('#pageKicker').textContent=t[0];$('#pageTitle').textContent=t[1];$('#today').textContent=new Intl.DateTimeFormat('en-PH',{weekday:'short',month:'short',day:'numeric',year:'numeric'}).format(new Date());
  const root=$('#content');root.innerHTML='<div class="panel"><div class="empty">Loading workspace…</div></div>';
  try{
    const builders={dashboard:dashboardView,requests:requestsView,schedules:schedulesView,panels:panelsView,rooms:roomsView,projects:projectsView,evaluations:evaluationsView,users:usersView,management:managementView,reports:reportsView};
    root.innerHTML=await builders[view]();
  }catch(e){root.innerHTML=`<div class="panel"><div class="empty danger">${esc(e.message)}</div></div>`}
}

async function dashboardView(){
  const d=await api('/api/dashboard');state.cache.dashboard=d;
  if(state.role==='student') return studentDashboard(d);
  if(state.role==='adviser') return adviserDashboard(d);
  if(state.role==='panel_member') return panelDashboard(d);
  return coordinatorDashboard(d);
}
function commonTimeline(rows,empty='No scheduled defenses.'){return rows?.length?rows.slice(0,6).map(s=>`<div class="timeline-item"><div class="timeline-date"><b>${dateFmt(s.defense_date)}</b><br>${timeFmt(s.start_time)}–${timeFmt(s.end_time)}</div><div class="timeline-main"><b>${esc(s.title)} · ${esc(s.defense_type||'Defense')}</b><small>${esc(s.title)}${s.room_name?' · '+esc(s.room_name):''}</small></div><div>${statusTag(s.status)}</div></div>`).join(''):`<div class="empty">${empty}</div>`}
function requestRows(rows,actions=false){const list=actions?(rows||[]).filter(r=>r.status==='Pending'):(rows||[]);return list.length?list.slice(0,6).map(r=>`<div class="request-item"><div class="request-main"><b>${esc(r.title)} · ${esc(r.defense_type)}</b><small>${esc(dateFmt(r.preferred_date))} · ${esc(timeFmt(r.preferred_time))}${r.review_feedback?' · '+esc(r.review_feedback):''}</small></div><div>${statusTag(r.status)}</div>${actions?`<div><button class="btn purple" data-review="${r.id}" data-review-status="approve">Approve</button> <button class="btn" data-review="${r.id}" data-review-status="return">Return</button></div>`:''}</div>`).join(''):`<div class="empty">${actions?'No requests are waiting for review.':'No requests found.'}</div>`}
function coordinatorDashboard(d){return `${pageHead('Coordinator workspace','Dashboard','Review requests, control schedules, assign panels and rooms, and monitor project delivery.','')}
<div class="grid-4">${stat('Active users',d.counts.active_users,'administrator-managed accounts')}${stat('Projects',d.counts.projects,'registered thesis & capstone records')}${stat('Pending requests',d.counts.pending_requests,'awaiting review')}${stat('Upcoming defenses',d.counts.upcoming,'scheduled defense activities','accent-number')}</div>
<div class="dash-grid"><section class="panel"><div class="panel-head"><div><h3>Defense schedule</h3><span>Upcoming and current defense activities</span></div><button class="btn" data-view="schedules">View all</button></div><div class="panel-body">${commonTimeline(d.schedules)}</div></section>
<section class="panel"><div class="panel-head"><div><h3>Requests needing review</h3><span>Adviser/student workflow</span></div><button class="btn" data-view="requests">Open requests</button></div><div class="panel-body">${requestRows(d.requests,true)}</div></section></div>
<div class="split-grid"><section class="panel"><div class="panel-head"><div><h3>Project plan</h3><span>Weeks 1–4 completed</span></div><button class="btn" data-view="management">Open plan</button></div><div class="panel-body"><div class="metric-row"><span>Project timeline</span><b>Aug 12 – Nov 4, 2026</b></div><div class="metric-row"><span>Estimated budget</span><b>${money(292700)}</b></div><div class="metric-row"><span>Tracked risks</span><b>12</b></div><div style="margin-top:10px"><div class="metric-row"><span>Current project progress</span><b>${Number(d.counts.progress||0)}%</b></div><div class="progress"><span style="width:${Number(d.counts.progress||0)}%"></span></div></div></div></section>
<section class="panel"><div class="panel-head"><div><h3>Workflow guardrails</h3><span>Access and scheduling controls</span></div></div><div class="panel-body"><div class="notice"><b>Administrator-issued accounts</b>Public registration is disabled. Schedule creation checks student, adviser, room, date, time, and panel availability before saving.</div></div></section></div>`}
function studentDashboard(d){const next=d.schedules?.find(s=>s.status==='Upcoming');return `${pageHead('Student workspace','Dashboard','Follow your defense request from preferred date and time through final result.','<button class="btn primary" data-modal="student-request">Request defense</button>')}
<div class="grid-4">${stat('My project',d.counts.projects,'registered project')}${stat('Requests',d.counts.pending_requests,'pending review')}${stat('Upcoming defense',d.counts.upcoming,next?dateFmt(next.defense_date):'not scheduled','accent-number')}${stat('Result records',state.cache.dashboard?.counts?.evaluations||0,'visible evaluation records')}</div>
<div class="dash-grid"><section class="panel"><div class="panel-head"><div><h3>Defense status</h3><span>${next?'Your next scheduled activity':'Your schedule will appear here after approval'}</span></div></div><div class="panel-body">${next?`<div class="project-card"><div><p class="micro">${esc(next.defense_type)}</p><h3 class="project-title">${esc(next.title)}</h3><div class="project-meta"><span class="chip">${dateFmt(next.defense_date)}</span><span class="chip">${timeFmt(next.start_time)}–${timeFmt(next.end_time)}</span><span class="chip">${esc(next.room_name||'Room TBA')}</span></div></div><div>${statusTag(next.status)}</div></div>`:'<div class="empty">No defense has been scheduled yet. Check your request status or submit a request.</div>'}</div></section>
<section class="panel"><div class="panel-head"><div><h3>My requests</h3><span>Preferred defense date & time</span></div><button class="btn" data-view="requests">View</button></div><div class="panel-body">${requestRows(d.requests)}</div></section></div>
<section class="panel" style="margin-top:15px"><div class="panel-head"><div><h3>Result</h3><span>Review your recorded defense result</span></div><button class="btn" data-view="evaluations">Open result</button></div><div class="panel-body"><div class="notice"><b>Result clarification</b>If you are not satisfied with a recorded result, use the result page to contact the adviser for clarification.</div></div></section>`}
function adviserDashboard(d){const students=[...(d.projects||[])].flatMap(p=>(p.students||[]).map(st=>({...st,project_title:p.title})));return `${pageHead('Adviser workspace','Dashboard','View your assigned students, monitor project status, review defense schedules, and provide evaluation/comments when assigned.','')}
<div class="grid-4">${stat('Assigned projects',d.counts.projects,'under your advising')}${stat('Assigned students',students.length,'students linked to your projects')}${stat('Upcoming defenses',d.counts.upcoming,'for assigned projects','accent-number')}${stat('My evaluations',d.counts.evaluations,'evaluation records')}</div>
<div class="dash-grid"><section class="panel"><div class="panel-head"><div><h3>Assigned students</h3><span>Students linked to projects you advise</span></div><button class="btn" data-view="projects">View projects</button></div><div class="panel-body">${students.length?students.slice(0,6).map(st=>`<div class="mini-row"><div><b>${esc(st.full_name)}</b><small>${esc(st.project_title)}</small></div></div>`).join(''):'<div class="empty">No assigned students.</div>'}</div></section><section class="panel"><div class="panel-head"><div><h3>Project status</h3><span>Monitor current status of assigned projects</span></div><button class="btn" data-view="projects">View</button></div><div class="panel-body">${d.projects?.length?d.projects.slice(0,5).map(p=>`<div class="mini-row"><div><b>${esc(p.title)}</b><small>${esc(p.type)}</small></div>${statusTag(p.status)}</div>`).join(''):'<div class="empty">No assigned projects.</div>'}</div></section></div>
<section class="panel" style="margin-top:15px"><div class="panel-head"><div><h3>Evaluation / comments</h3><span>Evaluate defenses only when you are the assigned adviser for the project</span></div><button class="btn" data-view="evaluations">Open evaluations</button></div><div class="panel-body"><div class="notice"><b>Assigned-project access only.</b> Your evaluation workspace is limited to defenses belonging to projects where you are the assigned adviser.</div></div></section>`}
function panelDashboard(d){const activeSchedules=(d.schedules||[]).filter(x=>x.status!=='Cancelled');const next=activeSchedules.find(x=>x.status==='Upcoming')||activeSchedules[0];return `${pageHead('Panel workspace','Dashboard','View assigned defenses, decide whether to proceed, and complete evaluations.','')}
<div class="grid-4">${stat('Assigned defenses',d.counts.assigned_defenses,'panel duties','accent-number')}${stat('Upcoming',d.counts.upcoming,'scheduled defenses')}${stat('My evaluations',d.counts.evaluations,'confirmed records')}${stat('Next room',next?.room_name||'—',next?dateFmt(next.defense_date):'no upcoming defense')}</div>
<div class="dash-grid"><section class="panel"><div class="panel-head"><div><h3>Assigned defenses</h3><span>Proceed or request reschedule</span></div><button class="btn" data-view="schedules">View</button></div><div class="panel-body">${activeSchedules.length?activeSchedules.slice(0,6).map(s=>`<div class="timeline-item"><div class="timeline-date"><b>${dateFmt(s.defense_date)}</b><br>${timeFmt(s.start_time)}</div><div class="timeline-main"><b>${esc(s.title)} · ${esc(s.defense_type)}</b><small>${esc(s.title)} · ${esc(s.room_name||'Room TBA')}</small></div><div>${s.panel_proceedance==='Pending'?`<button class="btn purple" data-proceed="${s.id}">Proceed</button>`:statusTag(s.panel_proceedance)}</div></div>`).join(''):'<div class="empty">No assigned defenses.</div>'}</div></section>
<section class="panel"><div class="panel-head"><div><h3>Evaluation</h3><span>Submit scores after conducting and observing the defense</span></div><button class="btn" data-view="evaluations">Open</button></div><div class="panel-body"><div class="notice"><b>Confirm before submission.</b>Your scores and comments are saved to the defense record and can be updated only through the evaluation workflow.</div></div></section></div>`}

async function projectsView(){const d=await api('/api/projects');state.cache.projects=d.projects||[];let add=state.role==='coordinator'?'<button class="btn primary" data-modal="project">Add project</button>':'';let extra='';return `${pageHead('Academic records',state.role==='student'?'My Project':'Projects',state.role==='student'?'Your registered thesis or capstone project.':state.role==='adviser'?'Projects currently assigned to your advising role.':state.role==='panel_member'?'Projects connected to your assigned defenses.':'Maintain thesis and capstone records.',add)}<section class="panel"><div class="panel-body">${d.projects?.length?d.projects.map(p=>`<div class="panel" style="margin-bottom:12px"><div class="panel-body project-card"><div><p class="micro">${esc(p.type)}</p><h3 class="project-title">${esc(p.title)}</h3><div class="project-meta"><span class="chip">Adviser: ${esc(p.adviser_name||'Unassigned')}</span><span class="chip">${esc(p.students?.map(s=>s.full_name).join(', ')||'No student')}</span></div></div><div>${statusTag(p.status)}${state.role==='coordinator'?`<div style="margin-top:10px"><select class="status-select" data-project-status="${p.id}"><option ${p.status==='Planning'?'selected':''}>Planning</option><option ${p.status==='Requirements'?'selected':''}>Requirements</option><option ${p.status==='Design'?'selected':''}>Design</option><option ${p.status==='Development'?'selected':''}>Development</option><option ${p.status==='Testing'?'selected':''}>Testing</option><option ${p.status==='Completed'?'selected':''}>Completed</option></select><button class="btn danger-btn" data-project-delete="${p.id}" style="margin-left:8px">Remove</button></div>`:''}</div></div></div>`).join(''):'<div class="empty">No projects available.</div>'}</div></section>${extra}`}
async function studentFeedbackHtml(){const d=await api('/api/feedback');return d.feedback?.length?d.feedback.map(f=>`<div class="timeline-item"><div class="timeline-date">${dateFmt(f.created_at?.slice?.(0,10)||'')}</div><div class="timeline-main"><b>${esc(f.title)}</b><small>${esc(f.feedback)}</small></div><div>${statusTag(f.status)} ${f.status==='Open'?`<button class="btn primary" data-feedback-resubmit="${f.id}">Resubmit</button>`:''}</div></div>`).join(''):'<div class="empty">No adviser feedback has been recorded.</div>'}
async function clarificationHtml(){const d=await api('/api/result-clarifications');return d.clarifications?.length?d.clarifications.map(c=>`<div class="timeline-item"><div class="timeline-date">${dateFmt(c.defense_date)}</div><div class="timeline-main"><b>${esc(c.title)} · ${esc(c.student_name)}</b><small>${esc(c.message)}${c.resolution_note?' · Response: '+esc(c.resolution_note):''}</small></div><div>${statusTag(c.status)} ${c.status==='Open'?`<button class="btn" data-clarification-resolve="${c.id}">Resolve</button>`:''}</div></div>`).join(''):'<div class="empty">No result clarification requests.</div>'}
async function feedbackHtml(){const d=await api('/api/feedback');return d.feedback?.length?d.feedback.map(f=>`<div class="timeline-item"><div class="timeline-date">${dateFmt(f.created_at?.slice?.(0,10)||'')}</div><div class="timeline-main"><b>${esc(f.title)}</b><small>${esc(f.feedback)}</small></div><div>${statusTag(f.status)} ${f.status==='Resubmitted'?`<button class="btn" data-feedback-satisfied="${f.id}">Satisfied</button>`:''}</div></div>`).join(''):'<div class="empty">No advising feedback has been recorded.</div>'}

async function requestsView(){const d=await api('/api/defense-requests');state.cache.requests=d.requests||[];const isStudent=state.role==='student';const isReviewer=state.role==='coordinator';return `${pageHead('Defense workflow',isStudent?'Defense Request':'Defense Requests',isStudent?'Submit your proposal or final-defense request with a preferred date and time.':'Review pending defense requests submitted by students.',isStudent?'<button class="btn primary" data-modal="student-request">New request</button>':'')}<section class="panel"><div class="panel-body table-wrap"><table class="data-table"><thead><tr><th>Project</th><th>Defense</th><th>Preferred schedule</th><th>Status</th><th>Feedback</th>${isReviewer?'<th>Decision</th>':isStudent?'<th>Action</th>':''}</tr></thead><tbody>${d.requests?.length?d.requests.map(r=>`<tr><td><b>${esc(r.title)}</b></span></td><td>${esc(r.defense_type)}</td><td>${dateFmt(r.preferred_date)}<br>${timeFmt(r.preferred_time)}</td><td>${statusTag(r.status)}</td><td class="muted">${esc(r.review_feedback||'—')}</td>${isReviewer?`<td>${r.status==='Pending'?`<button class="btn purple" data-review="${r.id}" data-review-status="approve">Approve</button> <button class="btn" data-review="${r.id}" data-review-status="return">Return</button>`:'—'}</td>`:isStudent?`<td>${r.status==='Returned'?`<button class="btn" data-resubmit-request="${r.id}">Revise & resubmit</button>`:'—'}</td>`:''}</tr>`).join(''):'<tr><td colspan="6"><div class="empty">No defense requests found.</div></td></tr>'}</tbody></table></div></section>`}

async function schedulesView(){
  const d=await api('/api/schedules');
  const allSchedules=d.schedules||[];
  const visibleSchedules=allSchedules.filter(s=>s.status!=='Cancelled');
  state.cache.schedules=visibleSchedules;
  const canManage=state.role==='coordinator';
  const canPanel=state.role==='panel_member';
  let reschedule=canPanel?'<span class="chip">Panel flow: Proceed / Request reschedule</span>':'';
  const action=canManage?'<button class="btn primary" data-modal="schedule">Add defense schedule</button>':'';
  return `${pageHead('Scheduling',state.role==='student'?'My Schedule':state.role==='panel_member'?'Assigned Defense':'Defense Schedule',state.role==='coordinator'?'Use approved requests for automatic scheduling, or create a defense schedule manually when needed.':canPanel?'Review assigned defenses and proceed or request reschedule.':'View the defense schedule related to your assigned work.',action)}
  <section class="panel"><div class="panel-body table-wrap"><table class="data-table"><thead><tr><th>Date</th><th>Project</th><th>Type</th><th>Time</th><th>Room</th><th>Status</th>${canPanel?'<th>Action</th>':''}${canManage?'<th>Manage</th>':''}</tr></thead><tbody>${visibleSchedules.length?visibleSchedules.map(s=>`<tr><td>${dateFmt(s.defense_date)}</td><td><b>${esc(s.title)}</b></td><td>${esc(s.defense_type)}</td><td>${timeFmt(s.start_time)}–${timeFmt(s.end_time)}</td><td>${esc(s.room_name||'Room TBA')}</td><td>${statusTag(s.status)}${s.panel_proceedance!=='Pending'?`<br>${statusTag(s.panel_proceedance)}`:''}</td>${canPanel?`<td>${s.panel_proceedance==='Pending'&&s.status==='Upcoming'?`<button class="btn purple" data-proceed="${s.id}">Proceed</button> <button class="btn" data-reschedule="${s.id}">Reschedule</button>`:s.status==='Completed'?`<button class="btn" data-view="evaluations">Evaluation</button>`:'—'}</td>`:''}${canManage?`<td>${s.status==='Upcoming'?`<button class="btn" data-schedule-edit="${s.id}">Edit</button> <button class="btn" data-room-assign="${s.id}">${s.room_id?'Change room':'Assign room'}</button> <button class="btn" data-cancel="${s.id}">Cancel</button>`:'—'}</td>`:''}</tr>`).join(''):'<tr><td colspan="8"><div class="empty">No active defense schedules found.</div></td></tr>'}</tbody></table></div></section>${canManage?`<section class="panel" style="margin-top:15px"><div class="panel-head"><div><h3>Reschedule requests</h3><span>Panel members can request a different defense time</span></div></div><div class="panel-body">${await rescheduleRequestsHtml()}</div></section>`:''}${reschedule?`<div style="margin-top:12px">${reschedule}</div>`:''}`}

async function rescheduleRequestsHtml(){const d=await api('/api/reschedule-requests');return d.requests?.length?d.requests.map(r=>`<div class="request-item"><div class="request-main"><b>${esc(r.requester_name)} · ${esc(r.title)}</b><small>Current: ${dateFmt(r.defense_date)} ${timeFmt(r.start_time)} · Requested: ${dateFmt(r.preferred_date)} ${timeFmt(r.preferred_time)}<br>${esc(r.reason)}</small></div>${statusTag(r.status)}${r.status==='Pending'?`<div><button class="btn purple" data-resched-review="${r.id}" data-status="Approved">Approve</button> <button class="btn" data-resched-review="${r.id}" data-status="Rejected">Reject</button></div>`:''}</div>`).join(''):'<div class="empty">No reschedule requests.</div>'}

async function panelsView(){const d=await api('/api/panels');state.cache.panels=d.assignments||[];const canAssign=state.role==='coordinator';return `${pageHead('Assignments','Panel Assignment',state.role==='coordinator'?'Assign chairperson, panel members, and adviser roles to defense schedules.':state.role==='panel_member'?'Your assigned defense roles.':state.role==='student'?'Panel members assigned to your defense.':'Panel assignment for your students.',canAssign?'<button class="btn primary" data-modal="panel">Assign panel</button>':'' )}<section class="panel"><div class="panel-body table-wrap"><table class="data-table"><thead><tr><th>Date</th><th>Project</th><th>Member</th><th>Panel role</th><th>Status</th>${canAssign?'<th>Action</th>':''}</tr></thead><tbody>${d.assignments?.length?d.assignments.map(a=>`<tr><td>${dateFmt(a.defense_date)}<br>${timeFmt(a.start_time)}</td><td><b>${esc(a.title)}</b></td><td>${esc(a.full_name)}<br><span class="muted">${esc(a.email)}</span></td><td>${esc(a.panel_role)}</td><td>${statusTag(a.status)}</td>${canAssign?`<td><button class="btn danger-btn" data-panel-delete="${a.id}">Remove</button></td>`:''}</tr>`).join(''):'<tr><td colspan="5"><div class="empty">No panel assignments found.</div></td></tr>'}</tbody></table></div></section>`}

async function roomsView(){const d=await api('/api/rooms');return `${pageHead('Facilities','Rooms','Manage defense rooms and availability.','<button class="btn primary" data-modal="room">Add room</button>')}<section class="panel"><div class="panel-body table-wrap"><table class="data-table"><thead><tr><th>Room</th><th>Location</th><th>Availability</th><th>Action</th></tr></thead><tbody>${d.rooms.map(r=>`<tr><td><b>${esc(r.name)}</b></td><td>${esc(r.location)}</td><td><label style="display:flex;align-items:center;gap:8px"><input type="checkbox" data-room="${r.id}" ${r.is_available?'checked':''}> <span class="muted">${r.is_available?'Available':'Unavailable'}</span></label></td><td><button class="btn" data-room-edit="${r.id}">Edit</button> <button class="btn danger-btn" data-room-delete="${r.id}">Delete</button></td></tr>`).join('')}</tbody></table></div></section>`}

async function evaluationsView(){const d=await api('/api/evaluations');const canSubmit=(state.role==='panel_member'||state.role==='adviser');return `${pageHead('Assessment',state.role==='student'?'Defense Result':state.role==='panel_member'?'Evaluation':'Evaluations',state.role==='student'?'Review recorded defense results and request clarification if needed.':canSubmit?'Submit confirmed evaluation and recommendations for assigned defenses.':'Review recorded defense evaluation results.',canSubmit?'<button class="btn primary" data-modal="evaluation">Submit evaluation</button>':'' )}<section class="panel"><div class="panel-body table-wrap"><table class="data-table"><thead><tr><th>Defense</th><th>Evaluator</th><th>Scores</th><th>Recommendation</th><th>Result</th><th>Comments</th>${state.role==='student'?'<th>Action</th>':''}</tr></thead><tbody>${d.evaluations?.length?d.evaluations.map(e=>{const avg=((Number(e.technical_score)+Number(e.presentation_score)+Number(e.documentation_score))/3).toFixed(1);return `<tr><td><b>${esc(e.title)}</b><br>${dateFmt(e.defense_date)} · ${esc(e.defense_type)}</td><td>${esc(e.evaluator_name)}</td><td>Technical ${Number(e.technical_score).toFixed(0)}<br>Presentation ${Number(e.presentation_score).toFixed(0)}<br>Documentation ${Number(e.documentation_score).toFixed(0)}<br><b>Average ${avg}</b></td><td>${esc(e.recommendation)}</td><td>${statusTag(e.defense_result||'—')}</td><td class="muted">${esc(e.comments||'—')}</td>${state.role==='student'?`<td><button class="btn" data-clarify="${e.schedule_id}">Not satisfied / Clarify</button></td>`:''}</tr>`}).join(''):'<tr><td colspan="7"><div class="empty">No evaluation result is available.</div></td></tr>'}</tbody></table></div></section>`}

async function usersView(){const d=await api('/api/users?_='+Date.now());return `${pageHead('Administration','User Management','Create, update, deactivate, and remove system accounts. Public registration is disabled.','<button class="btn primary" data-modal="user">Create account</button>')}<section class="panel"><div class="panel-body table-wrap"><table class="data-table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody>${d.users.map(u=>`<tr><td><div class="user-name-cell">${avatarMarkup(u)}<b>${esc(u.full_name)}</b></div></td><td>${esc(u.email)}</td><td>${roleLabel(u.role)}</td><td>${u.is_active?statusTag('Active'):statusTag('At Risk')}</td><td><div class="table-actions">${u.id!==state.user.id?`<button class="btn" data-user-edit="${u.id}">Edit</button><button class="btn" data-user-toggle="${u.id}" data-active="${u.is_active}">${u.is_active?'Deactivate':'Activate'}</button><button class="btn danger-btn" data-user-delete="${u.id}">Delete</button>`:'<span class="muted">Current account</span>'}</div></td></tr>`).join('')}</tbody></table></div></section>`}

async function managementView(){const d=await api('/api/management');const completed=d.weekly.filter(w=>w.status==='Completed').length;return `${pageHead('Project controls','Project Plan','Your six required project-management documents in one workspace.','')}
<div class="grid-4">${stat('WBS phases','7','major phases')}${stat('Project weeks','12','Aug 12 – Nov 4')}${stat('Budget',money(d.budgetTotal),'estimated total')}${stat('Completed weeks',completed,'current tracker status','accent-number')}</div>
<div class="management-grid"><section class="panel"><div class="panel-head"><div><h3>Work Breakdown Structure</h3><span>Seven major phases and work packages</span></div></div><div class="panel-body table-wrap"><table class="data-table"><thead><tr><th>Code</th><th>Work package</th><th>Target dates</th><th>Status</th></tr></thead><tbody>${d.wbs.map(w=>`<tr><td><b>${esc(w.code)}</b></td><td>${w.phase?'<b>':''}${esc(w.item)}${w.phase?'</b>':''}</td><td>${esc(w.target_dates)}</td><td>${statusTag(w.status)}</td></tr>`).join('')}</tbody></table></div></section>
<section class="panel"><div class="panel-head"><div><h3>Gantt Chart</h3><span>12-week delivery timeline</span></div></div><div class="panel-body table-wrap"><table class="data-table"><thead><tr><th>Activity</th>${Array.from({length:12},(_,i)=>`<th>W${i+1}</th>`).join('')}</tr></thead><tbody>${d.gantt.map(g=>`<tr><td><b>${esc(g.activity)}</b></td>${Array.from({length:12},(_,i)=>`<td>${i+1>=g.week_start&&i+1<=g.week_end?`<span class="status ${g.status.toLowerCase().replace(/\s+/g,'')}">●</span>`:'—'}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>
<section class="panel"><div class="panel-head"><div><h3>Budget Plan</h3><span>Estimated project cost</span></div><strong>${money(d.budgetTotal)}</strong></div><div class="panel-body table-wrap"><table class="data-table"><thead><tr><th>Category</th><th>Description</th><th>Qty</th><th>Unit cost</th><th>Total</th></tr></thead><tbody>${d.budget.map(b=>`<tr><td><b>${esc(b.category)}</b></td><td>${esc(b.description)}</td><td>${esc(b.quantity)}</td><td>${money(b.unit_cost)}</td><td><b>${money(b.total)}</b></td></tr>`).join('')}</tbody></table></div></section>
<section class="panel"><div class="panel-head"><div><h3>Risk Register</h3><span>R1–R12 with mitigation and owners</span></div></div><div class="panel-body table-wrap"><table class="data-table"><thead><tr><th>ID</th><th>Risk</th><th>Category</th><th>Likelihood</th><th>Impact</th><th>Level</th><th>Mitigation</th><th>Owner</th></tr></thead><tbody>${d.risks.map(r=>`<tr><td><b>${esc(r.id)}</b></td><td>${esc(r.description)}</td><td>${esc(r.category)}</td><td>${esc(r.likelihood)}</td><td>${esc(r.impact)}</td><td>${statusTag(r.risk_level)}</td><td>${esc(r.mitigation)}</td><td>${esc(r.owner)}</td></tr>`).join('')}</tbody></table></div></section>
<section class="panel"><div class="panel-head"><div><h3>System Flowchart</h3><span>Role flow used by the application</span></div></div><div class="flow-wrap"><img src="/assets/system-flowchart.png" alt="Student, Adviser, Coordinator, and Panel flowchart"></div></section>
<section class="panel"><div class="panel-head"><div><h3>Weekly Tracker</h3><span>Weeks 1–4 are completed</span></div></div><div class="panel-body table-wrap"><table class="data-table"><thead><tr><th>Week</th><th>Focus</th><th>Expected output</th><th>Status</th><th>Progress</th><th>Update</th></tr></thead><tbody>${d.weekly.map(w=>`<tr><td><b>Week ${w.week}</b></td><td>${esc(w.focus)}</td><td>${esc(w.expected_output)}</td><td>${statusTag(w.status)}</td><td>${w.progress}%</td><td><select data-week-status="${w.week}"><option ${w.status==='Not started'?'selected':''}>Not started</option><option ${w.status==='In Progress'?'selected':''}>In Progress</option><option ${w.status==='Completed'?'selected':''}>Completed</option><option ${w.status==='At Risk'?'selected':''}>At Risk</option></select></td></tr>`).join('')}</tbody></table></div></section></div>`}

async function reportsView(){const d=await api('/api/reports/summary');return `${pageHead('Reporting','Reports','Complete defense-related reports required by the project scope.','<button class="btn primary" data-export>Export all reports</button>')}<div class="grid-4">${stat('Projects',d.projects,'registered projects')}${stat('Defense requests',d.requests,'recorded requests')}${stat('Schedules',d.schedules,'active schedules')}${stat('Evaluations',d.evaluations,'recorded evaluations')}</div><div class="report-grid" style="margin-top:15px"><section class="panel report-card"><div class="panel-head"><div><h3>Defense Schedule Report</h3><span>Dates, times, projects, rooms and status</span></div><button class="btn" data-report="defense-schedule">View</button></div></section><section class="panel report-card"><div class="panel-head"><div><h3>Panel Assignment Report</h3><span>Chairperson, panel members and adviser</span></div><button class="btn" data-report="panel-assignment">View</button></div></section><section class="panel report-card"><div class="panel-head"><div><h3>Student Status Report</h3><span>Projects, students, advisers and status</span></div><button class="btn" data-report="student-status">View</button></div></section><section class="panel report-card"><div class="panel-head"><div><h3>Evaluation Report</h3><span>Scores, recommendations and results</span></div><button class="btn" data-report="evaluation">View</button></div></section></div><section id="reportResult" class="panel" style="margin-top:15px"><div class="empty">Choose a report to preview its complete records.</div></section>`}

function openModal(type){
  const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.id='modal';
  wrap.addEventListener('click',e=>{if(e.target===wrap)wrap.remove()});
  let title='',body='',action='';
  if(type==='user'){title='Create account';action='user';body=`<div class="modal-form"><label>Full name<input id="f-name" required></label><label>Email address<input id="f-email" type="email" required></label><label>Password<input id="f-password" type="password" minlength="8" required></label><label class="full">Panel availability <span class="field-note">Optional</span><textarea id="f-availability" placeholder="Example: Mon–Fri, 9:00 AM–5:00 PM"></textarea></label><label>Role<select id="f-role"><option value="student">Student</option><option value="adviser">Adviser</option><option value="panel_member">Panel Member</option><option value="coordinator">Coordinator / Administrator</option></select></label><div class="full notice"><b>Administrator-issued account</b>This account is created by the Coordinator / Administrator. Public registration remains disabled.</div></div>`}
  if(type==='project'){
    title='Add project';action='project';body=`<div class="modal-form"><label>Type<select id="f-type"><option>Thesis</option><option>Capstone</option></select></label><label>Adviser<select id="f-adviser"><option value="">Select adviser</option></select></label><label class="full">Project title<input id="f-title" placeholder="Enter thesis or capstone title" required></label><label class="full">Students <span class="field-note">Select up to 3</span><select id="f-students" class="multi-select" multiple size="7"></select></label><div class="full notice"><b>Project group</b>Select the student members who belong to this thesis or capstone project. You may select up to three active students.</div></div>`
  }
  if(type==='student-request'){title='Submit defense request';action='student-request';body=`<div class="modal-form"><label class="full">Project<select id="f-project"><option value="">Loading assigned projects…</option></select></label><div id="student-project-note" class="full muted"></div><label>Defense type<select id="f-defense-type"><option>Proposal Defense</option><option>Final Defense</option></select></label><label>Preferred date<input id="f-date" type="date"></label><label>Preferred time<input id="f-time" type="time"></label><label class="full">Reason / notes<textarea id="f-reason" placeholder="Optional details for the reviewer"></textarea></label></div>`}
  if(type==='room'){title='Add room';action='room';body=`<div class="modal-form"><label>Room name<input id="f-name"></label><label class="full">Location<input id="f-location"></label></div>`}
  if(type==='schedule'){title='Add defense schedule';action='schedule';body=`<div class="modal-form"><label class="full">Project<select id="f-schedule-project"><option value="">Loading projects…</option></select></label><label>Defense type<select id="f-schedule-type"><option>Proposal Defense</option><option>Final Defense</option></select></label><label>Defense date<input id="f-schedule-date" type="date"></label><label>Start time<input id="f-schedule-start" type="time"></label><label>End time<input id="f-schedule-end" type="time"></label><label>Room<select id="f-schedule-room"><option value="">No room assigned</option></select></label><label class="full">Notes<textarea id="f-schedule-notes" placeholder="Optional scheduling notes"></textarea></label><div class="full notice"><b>Manual scheduling</b>This creates a defense schedule directly for the selected project. Approved student requests can still generate schedules automatically.</div></div>`}
  
  if(type==='panel'){title='Assign panel';action='panel';body=`<div class="modal-form"><label class="full">Project<select id="f-panel-project"><option value="">Loading projects…</option></select></label><label class="full">Defense schedule<select id="f-schedule"><option value="">Select a project first</option></select></label><label>Defense date<input id="f-panel-date" type="date" readonly></label><label>Defense time<input id="f-panel-time" type="text" readonly placeholder="Select a defense schedule"></label><label>Person<select id="f-member"></select></label><label>Assignment<select id="f-panel-role"><option>Chairperson</option><option>Panel Member</option><option>Adviser</option></select></label><div class="full notice"><b>Assignment rules</b> Select the project and its defense schedule first. The defense date and time are taken directly from that schedule and cannot be edited here. Chairperson and Panel Member use panel-member accounts. Adviser uses the adviser assigned to the selected project.</div></div>`}
  if(type==='evaluation'){title='Submit evaluation';action='evaluation';body=`<div class="modal-form"><label class="full">Assigned defense<select id="f-schedule"></select></label><label>Technical score<input id="f-technical" type="number" min="0" max="100"></label><label>Presentation score<input id="f-presentation" type="number" min="0" max="100"></label><label>Documentation score<input id="f-documentation" type="number" min="0" max="100"></label><label>Recommendation<select id="f-recommendation"><option>Approved</option><option>For Revision</option><option>Re-defense Required</option></select></label><label>Defense result<select id="f-defense-result"><option>Passed</option><option>Failed</option><option>For Revision</option><option>Re-defense Required</option></select></label><label class="full">Comments<textarea id="f-comments"></textarea></label><div class="full notice"><b>Confirmation step</b> Review the scores and comments before you submit. The submission is recorded as the confirmed evaluation.</div></div>`;loadEvaluationOptions()}
  if(type==='feedback'){title='Provide advising feedback';action='feedback';body=`<div class="modal-form"><label class="full">Assigned project<select id="f-project"></select></label><label class="full">Feedback<textarea id="f-feedback" placeholder="Write clear advising feedback and revision points."></textarea></label></div>`;loadFeedbackProjects()}
  wrap.innerHTML=`<div class="modal"><div class="modal-head"><h3>${title}</h3><button class="modal-close" data-close-modal>×</button></div>${body}<div class="modal-form"><div class="modal-actions"><button class="btn" data-close-modal>Cancel</button><button class="btn primary" data-submit-modal="${action}">${type==='evaluation'?'Submit evaluation':'Save'}</button></div></div></div>`;
  document.body.appendChild(wrap);
  if(type==='project') loadProjectPeople().catch(err=>toast(err.message));
  if(type==='schedule') loadScheduleCreateOptions().catch(err=>toast(err.message));
  if(type==='student-request') loadStudentProjects().catch(err=>{const note=$('#student-project-note');if(note)note.textContent=err.message;toast(err.message)});
  if(type==='panel') loadPanelOptions().catch(err=>toast(err.message));
}
async function openScheduleEdit(id){const d=await api('/api/schedules');const s=d.schedules.find(x=>Number(x.id)===Number(id));if(!s)return toast('Schedule not found.');const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.id='modal';wrap.innerHTML=`<div class="modal"><div class="modal-head"><div><p class="micro">DEFENSE SCHEDULE</p><h3>Edit schedule</h3></div><button class="modal-close" data-close-modal>×</button></div><div class="modal-form"><label class="full">Project<select id="se-project"></select></label><label>Defense type<select id="se-type"><option>Proposal Defense</option><option>Final Defense</option></select></label><label>Date<input id="se-date" type="date" value="${String(s.defense_date).slice(0,10)}"></label><label>Start time<input id="se-start" type="time" value="${String(s.start_time).slice(0,5)}"></label><label>End time<input id="se-end" type="time" value="${String(s.end_time).slice(0,5)}"></label><label>Room<select id="se-room"></select></label><label class="full">Notes<textarea id="se-notes">${esc(s.notes||'')}</textarea></label><div class="modal-actions"><button class="btn" data-close-modal>Cancel</button><button class="btn primary" id="saveScheduleEdit">Save changes</button></div></div></div>`;document.body.appendChild(wrap);const p=await api('/api/projects');$('#se-project').innerHTML=p.projects.map(x=>`<option value="${x.id}" ${Number(x.id)===Number(s.project_id)?'selected':''}>${esc(x.title)}</option>`).join('');$('#se-type').value=s.defense_type;const refreshEditRooms=async()=>{const r=await api(`/api/rooms?date=${encodeURIComponent($('#se-date').value)}&start=${encodeURIComponent($('#se-start').value)}&end=${encodeURIComponent($('#se-end').value)}&exclude_id=${encodeURIComponent(id)}`);$('#se-room').innerHTML='<option value="">No room assigned</option>'+(r.rooms||[]).filter(x=>x.is_available||Number(x.id)===Number(s.room_id)).map(x=>`<option value="${x.id}" ${Number(x.id)===Number(s.room_id)?'selected':''} ${x.occupied&&Number(x.id)!==Number(s.room_id)?'disabled':''}>${esc(x.name)} · ${esc(x.location)}${x.occupied&&Number(x.id)!==Number(s.room_id)?' · Occupied':''}</option>`).join('');};await refreshEditRooms();['#se-date','#se-start','#se-end'].forEach(sel=>$(sel)?.addEventListener('change',refreshEditRooms));$('#saveScheduleEdit').onclick=async()=>{try{await api('/api/schedules/'+id,{method:'PATCH',body:JSON.stringify({project_id:Number($('#se-project').value),defense_type:$('#se-type').value,defense_date:$('#se-date').value,start_time:$('#se-start').value,end_time:$('#se-end').value,room_id:Number($('#se-room').value)||null,notes:$('#se-notes').value})});wrap.remove();toast('Schedule updated.');renderView('schedules')}catch(e){toast(e.message)}};}
async function loadProjectPeople(){const [a,s]=await Promise.all([api('/api/advisers'),api('/api/students')]);const adviser=$('#f-adviser');const students=$('#f-students');if(adviser)adviser.innerHTML=`<option value="">Select adviser</option>${a.users.map(u=>`<option value="${u.id}">${esc(u.full_name)} · ${esc(u.email)}</option>`).join('')}`;if(students)students.innerHTML=s.users.map(u=>`<option value="${u.id}">${esc(u.full_name)} · ${esc(u.email)}</option>`).join('');}
async function loadStudentProjects(){const d=await api('/api/my-projects');const s=$('#f-project');const note=$('#student-project-note');if(!s)return;if(!d.projects.length){s.innerHTML='<option value="">No assigned project available</option>';s.disabled=true;if(note)note.innerHTML='<span class="notice-inline">You do not have a project assigned yet. A Coordinator must add you to a project before you can request a defense.</span>';const submit=document.querySelector('[data-submit-modal="student-request"]');if(submit)submit.disabled=true;return;}s.disabled=false;s.innerHTML=d.projects.map(p=>`<option value="${p.id}">${esc(p.title)} · ${esc(p.type)} · Adviser: ${esc(p.adviser_name)}</option>`).join('');if(note)note.textContent=`${d.projects.length} assigned project${d.projects.length===1?'':'s'} available for a defense request.`;}
async function loadScheduleCreateOptions(){const p=await api('/api/projects');const pe=$('#f-schedule-project');if(pe)pe.innerHTML=p.projects?.length?p.projects.map(x=>`<option value="${x.id}">${esc(x.title)} · ${esc(x.type||'Project')}</option>`).join(''):'<option value="">No projects available</option>';await refreshScheduleRooms();}
async function refreshScheduleRooms(){const re=$('#f-schedule-room');if(!re)return;const date=$('#f-schedule-date')?.value||'',start=$('#f-schedule-start')?.value||'',end=$('#f-schedule-end')?.value||'';const r=await api(`/api/rooms?date=${encodeURIComponent(date)}&start=${encodeURIComponent(start)}&end=${encodeURIComponent(end)}`);const rooms=(r.rooms||[]);const hasSlot=!!(date&&start&&end);re.innerHTML='<option value="">No room assigned</option>'+rooms.filter(x=>x.is_available).map(x=>`<option value="${x.id}" ${x.occupied?'disabled':''}>${esc(x.name)} · ${esc(x.location)}${x.occupied?' · Occupied':''}</option>`).join('');if(hasSlot&&!rooms.some(x=>x.is_available&&!x.occupied))re.innerHTML='<option value="">No rooms available for this time</option>';}
async function loadScheduleOptions(){}
async function loadPanelOptions(){const m=await api('/api/panel-options');const projectEl=$('#f-panel-project');const scheduleEl=$('#f-schedule');if(!projectEl||!scheduleEl)return;const options={panelMembers:m.panelMembers||[],advisers:m.advisers||[]};const schedules=(m.schedules||[]).filter(x=>x.status!=='Cancelled'&&x.status!=='Completed');const projects=[...new Map(schedules.map(x=>[Number(x.project_id),{id:Number(x.project_id),title:x.title,type:x.type}])).values()];projectEl.innerHTML=projects.length?projects.map(x=>`<option value="${x.id}">${esc(x.title)} · ${esc(x.type||'Project')}</option>`).join(''):'<option value="">No active defense schedule exists yet</option>';projectEl.disabled=!projects.length;const fillSchedules=()=>{const pid=Number(projectEl.value);const matches=schedules.filter(x=>Number(x.project_id)===pid);scheduleEl.innerHTML=matches.length?matches.map(x=>`<option value="${x.id}">${dateFmt(x.defense_date)} · ${esc(x.title)} · ${timeFmt(x.start_time)}–${timeFmt(x.end_time)}</option>`).join(''):'<option value="">No defense schedule for this project</option>';scheduleEl.disabled=!matches.length;const schedule=matches[0];renderPanelMemberOptions(schedule,options)};projectEl.onchange=fillSchedules;scheduleEl.onchange=()=>{const schedule=schedules.find(x=>Number(x.id)===Number(scheduleEl.value));renderPanelMemberOptions(schedule,options)};fillSchedules();}
function renderPanelMemberOptions(schedule,options){const el=$('#f-member');if(!el)return;const dateEl=$('#f-panel-date');const timeEl=$('#f-panel-time');if(dateEl)dateEl.value=schedule?.defense_date?String(schedule.defense_date).slice(0,10):'';if(timeEl)timeEl.value=schedule?(timeFmt(schedule.start_time)+'–'+timeFmt(schedule.end_time)):'';const adviser=options.advisers.find(a=>Number(a.id)===Number(schedule?.adviser_id));const panels=options.panelMembers||[];const role=$('#f-panel-role')?.value;let html='';if(role==='Adviser'){html=adviser?`<option value="${adviser.id}">${esc(adviser.full_name)} · Adviser</option>`:'<option value="">Assigned adviser unavailable</option>';}else{html=panels.map(u=>`<option value="${u.id}">${esc(u.full_name)} · Panel Member</option>`).join('');}el.innerHTML=html;}
async function loadEvaluationOptions(){const s=await api('/api/schedules');const eligible=(s.schedules||[]).filter(x=>x.status!=='Cancelled' && x.status!=='Completed' && (state.role==='adviser' ? Number(x.adviser_id)===Number(state.user?.id) : true));setTimeout(()=>{const el=$('#f-schedule');if(el)el.innerHTML=eligible.length?eligible.map(x=>`<option value="${x.id}">${dateFmt(x.defense_date)} · ${esc(x.title)} · ${esc(x.defense_type)}</option>`).join(''):'<option value="">No assigned defenses available</option>'},0)}
async function loadFeedbackProjects(){const p=await api('/api/projects');setTimeout(()=>{const el=$('#f-project');if(el)el.innerHTML=p.projects.map(x=>`<option value="${x.id}">${esc(x.title)}</option>`).join('')},0)}

async function submitModal(type){
  try{
    if(type==='user'){await api('/api/users',{method:'POST',body:JSON.stringify({full_name:$('#f-name').value,email:$('#f-email').value,password:$('#f-password').value,role:$('#f-role').value,panel_availability:$('#f-availability')?.value||''})});toast('Account created.');}
    if(type==='project'){const ids=[...$('#f-students').selectedOptions].map(o=>Number(o.value)).filter(Boolean);if(ids.length<1||ids.length>3) throw new Error('Select 1 to 3 students.');if(!$('#f-adviser').value) throw new Error('Select an adviser.');await api('/api/projects',{method:'POST',body:JSON.stringify({title:$('#f-title').value,type:$('#f-type').value,adviser_id:Number($('#f-adviser').value),student_ids:ids})});toast('Project added.');}
    if(type==='student-request'){const projectId=Number($('#f-project').value);if(!projectId)throw new Error('Select an assigned project before submitting your request.');await api('/api/defense-requests',{method:'POST',body:JSON.stringify({project_id:projectId,defense_type:$('#f-defense-type').value,preferred_date:$('#f-date').value,preferred_time:$('#f-time').value,reason:$('#f-reason').value})});toast('Defense request submitted.');}
    if(type==='room'){await api('/api/rooms',{method:'POST',body:JSON.stringify({name:$('#f-name').value,location:$('#f-location').value})});toast('Room added.');}
    if(type==='schedule'){
      const payload={project_id:Number($('#f-schedule-project').value),defense_type:$('#f-schedule-type').value,defense_date:$('#f-schedule-date').value,start_time:$('#f-schedule-start').value,end_time:$('#f-schedule-end').value,room_id:Number($('#f-schedule-room').value)||null,notes:$('#f-schedule-notes').value};
      if(!payload.project_id) throw new Error('Select a project before saving the defense schedule.');
      if(!payload.defense_date||!payload.start_time||!payload.end_time) throw new Error('Enter the defense date, start time, and end time.');
      await api('/api/schedules',{method:'POST',body:JSON.stringify(payload)});
      $('#modal')?.remove();
      toast('Defense schedule saved.');
      await renderView('schedules');
      return;
    }
    if(type==='panel'){await api('/api/panels',{method:'POST',body:JSON.stringify({schedule_id:Number($('#f-schedule').value),user_id:Number($('#f-member').value),panel_role:$('#f-panel-role').value})});toast('Panel assignment saved.');}
    if(type==='evaluation'){await api('/api/evaluations',{method:'POST',body:JSON.stringify({schedule_id:Number($('#f-schedule').value),technical_score:Number($('#f-technical').value),presentation_score:Number($('#f-presentation').value),documentation_score:Number($('#f-documentation').value),comments:$('#f-comments').value,recommendation:$('#f-recommendation').value,defense_result:$('#f-defense-result').value})});toast('Evaluation submitted.');}
    if(type==='feedback'){await api('/api/feedback',{method:'POST',body:JSON.stringify({project_id:Number($('#f-project').value),feedback:$('#f-feedback').value})});toast('Feedback recorded.');}
    $('#modal')?.remove();renderView(state.view);
  }catch(e){toast(e.message)}
}
function openUserEdit(id){
  if(state.role!=='coordinator') return;
  api('/api/users?_='+Date.now()).then(d=>{
    const u=d.users.find(x=>Number(x.id)===Number(id));
    if(!u)return toast('User not found.');
    const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.id='userEditModal';
    wrap.innerHTML=`<div class="modal profile-modal"><div class="modal-head"><div><p class="micro">ADMINISTRATION</p><h3>Edit user</h3></div><button class="modal-close" data-close-user-edit>×</button></div>
      <form id="userEditForm" class="modal-form">
        <div class="profile-summary full"><div class="profile-large-avatar">${u.profile_image?`<img src="/api/users/${u.id}/profile-image?v=${Date.now()}" alt="${esc(u.full_name)} profile picture" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'"><span class="avatar-fallback" style="display:none">${esc(initials(u.full_name))}</span>`:esc(initials(u.full_name))}</div><div><b>${esc(roleLabel(u.role))}</b><span>Coordinator-managed account</span></div></div>
        <label>Full name<input id="ue-name" value="${esc(u.full_name)}" required></label>
        <label>Email address<input id="ue-email" type="email" value="${esc(u.email)}" required></label>
        <label>Role<select id="ue-role"><option value="student">Student</option><option value="adviser">Adviser</option><option value="panel_member">Panel Member</option><option value="coordinator">Coordinator / Administrator</option></select></label>
        <div class="password-divider full"><span>Optional password reset</span></div><label class="full">Panel availability <span class="field-note">For panel members</span><textarea id="ue-availability" placeholder="Example: Mon–Fri, 9:00 AM–5:00 PM"></textarea></label>
        <label class="full">New password<input id="ue-password" type="password" autocomplete="new-password" placeholder="Leave blank to keep current password"></label>
        <div class="modal-actions"><button type="button" class="btn" data-close-user-edit>Cancel</button><button type="submit" class="btn primary">Save user</button></div>
      </form></div>`;
    document.body.appendChild(wrap);
    if($('#ue-role')) $('#ue-role').value=u.role;
    if($('#ue-availability')) $('#ue-availability').value=u.panel_availability||'';
    $('#userEditForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/users/'+u.id,{method:'PATCH',body:JSON.stringify({full_name:$('#ue-name').value,email:$('#ue-email').value,password:$('#ue-password').value,panel_availability:$('#ue-availability')?.value||'',role:$('#ue-role').value})});wrap.remove();toast('User account updated.');renderView('users')}catch(err){toast(err.message)}};
  }).catch(err=>toast(err.message));
}

function openProfile(){
  const u=state.user;
  const coordinator=state.role==='coordinator';
  const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.id='profileModal';
  wrap.innerHTML=`<div class="modal profile-modal"><div class="modal-head"><div><p class="micro">ACCOUNT</p><h3>My profile</h3></div><button class="modal-close" data-close-profile>×</button></div>
    <form id="profileForm" class="modal-form">
      <div class="profile-summary full"><div class="profile-large-avatar" id="profileAvatarPreview">${u.profile_image?`<img src="${esc(u.profile_image)}" alt="Profile picture"><span class="avatar-fallback" style="display:none">${esc(initials(u.full_name))}</span>`:esc(initials(u.full_name))}</div><div><b>${esc(roleLabel(u.role))}</b><span>${coordinator?'Coordinator accounts can update their own identity details.':'Name and email are managed by the Coordinator / Administrator.'}</span></div></div>
      <label class="full">Profile picture
        <div class="profile-upload-row">
          <input id="p-image" type="file" accept="image/png,image/jpeg,image/webp">
          ${u.profile_image?'<button type="button" class="btn danger-outline" id="remove-profile-image">Remove picture</button>':''}
        </div>
        <small class="field-note">PNG, JPG, or WebP. Maximum 600 KB.</small>
      </label>
      <label>Full name<input id="p-name" value="${esc(u.full_name)}" ${coordinator?'':'readonly'} required></label>
      <label>Email address<input id="p-email" type="email" value="${esc(u.email)}" ${coordinator?'':'readonly'} required></label>
      <div class="password-divider full"><span>Password</span></div>
      <label>Current password<input id="p-current" type="password" autocomplete="current-password" placeholder="Required only to change password"></label>
      <label>New password<input id="p-new" type="password" autocomplete="new-password" placeholder="Leave blank to keep current"></label>
      <label class="full">Confirm new password<input id="p-confirm" type="password" autocomplete="new-password" placeholder="Re-enter the new password"></label>
      <div class="modal-actions"><button type="button" class="btn" data-close-profile>Cancel</button><button type="submit" class="btn primary">Save changes</button></div>
    </form></div>`;
  document.body.appendChild(wrap);
  let removeProfileImage=false;
  $('#p-image').onchange=()=>{
    const file=$('#p-image').files?.[0]; if(!file)return;
    removeProfileImage=false;
    if(!['image/png','image/jpeg','image/webp'].includes(file.type)){toast('Use a PNG, JPG, or WebP image.');$('#p-image').value='';return;}
    if(file.size>600*1024){toast('Profile image must be 600 KB or smaller.');$('#p-image').value='';return;}
    const reader=new FileReader(); reader.onload=()=>$('#profileAvatarPreview').innerHTML=`<img src="${reader.result}" alt="Profile picture">`; reader.readAsDataURL(file);
  };
  $('#remove-profile-image')?.addEventListener('click',()=>{
    removeProfileImage=true;
    $('#p-image').value='';
    $('#profileAvatarPreview').textContent=initials(u.full_name);
    toast('Profile picture will be removed when you save.');
  });
  $('#profileForm').onsubmit=async (e)=>{
    e.preventDefault();
    const newPass=$('#p-new').value, confirm=$('#p-confirm').value;
    if(newPass!==confirm){toast('New passwords do not match.');return;}
    try{
      const payload={current_password:$('#p-current').value,new_password:newPass};
      if(coordinator){payload.full_name=$('#p-name').value;payload.email=$('#p-email').value;}
      const file=$('#p-image').files?.[0];
      if(removeProfileImage) payload.profile_image=null;
      else if(file){ payload.profile_image=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);}); }
      const d=await api('/api/profile',{method:'PATCH',body:JSON.stringify(payload)});
      state.user=d.user;showApp();wrap.remove();toast('Profile updated.');
    }catch(err){toast(err.message)}
  };
}
async function openResubmitRequest(id){const d=await api('/api/defense-requests');const r=d.requests.find(x=>Number(x.id)===Number(id));if(!r)return toast('Request not found.');const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.id='modal';wrap.innerHTML=`<div class="modal"><div class="modal-head"><h3>Revise & resubmit request</h3><button class="modal-close" data-close-modal>×</button></div><div class="modal-form"><div class="full notice"><b>${esc(r.title)}</b><br>${esc(r.review_feedback||'')}</div><label>Preferred date<input id="rr-date" type="date" value="${String(r.preferred_date).slice(0,10)}"></label><label>Preferred time<input id="rr-time" type="time" value="${String(r.preferred_time).slice(0,5)}"></label><label class="full">Reason / revisions<textarea id="rr-reason">${esc(r.reason||'')}</textarea></label><div class="modal-actions"><button class="btn" data-close-modal>Cancel</button><button class="btn primary" id="rr-send">Resubmit request</button></div></div></div>`;document.body.appendChild(wrap);$('#rr-send').onclick=async()=>{try{await api('/api/defense-requests/'+id+'/resubmit',{method:'PATCH',body:JSON.stringify({preferred_date:$('#rr-date').value,preferred_time:$('#rr-time').value,reason:$('#rr-reason').value})});wrap.remove();toast('Defense request resubmitted.');renderView('requests')}catch(e){toast(e.message)}};}
function openClarificationResolve(id){const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.id='modal';wrap.innerHTML=`<div class="modal"><div class="modal-head"><h3>Resolve clarification</h3><button class="modal-close" data-close-modal>×</button></div><div class="modal-form"><label class="full">Response<textarea id="cr-note" placeholder="Provide a clear response to the student's question."></textarea></label><div class="modal-actions"><button class="btn" data-close-modal>Cancel</button><button class="btn primary" id="cr-save">Mark resolved</button></div></div></div>`;document.body.appendChild(wrap);$('#cr-save').onclick=async()=>{try{await api('/api/result-clarifications/'+id,{method:'PATCH',body:JSON.stringify({resolution_note:$('#cr-note').value})});wrap.remove();toast('Clarification resolved.');renderView('projects')}catch(e){toast(e.message)}};}
function openReviewModal(id, approving){
  const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.id='reviewModal';
  const options=approving?['Approved — ready for scheduling','Approved — minor notes','Approved — proceed with defense']:[ 'Please revise and resubmit','Missing or incomplete requirements','Preferred date/time needs adjustment','Additional adviser/coordinator review required','Other'];
  wrap.innerHTML=`<div class="modal"><div class="modal-head"><div><p class="micro">DEFENSE REQUEST</p><h3>${approving?'Approve request':'Return request'}</h3></div><button class="modal-close" data-close-review>×</button></div><div class="modal-form"><label class="full">Feedback<select id="review-feedback-choice">${options.map(o=>`<option>${esc(o)}</option>`).join('')}<option value="__custom__">Custom feedback…</option></select></label><label class="full" id="review-custom-wrap" style="display:none">Additional note<textarea id="review-custom" placeholder="Add specific feedback for the student."></textarea></label><div class="full notice"><b>${approving?'Automatic scheduling':'Request returned'}</b>${approving?'Approving creates the defense schedule automatically from the student’s preferred date and time. The room and panel remain pending assignment.':'Returning the request removes it from the review queue and sends the selected feedback back to the student.'}</div><div class="modal-actions"><button class="btn" data-close-review>Cancel</button><button class="btn primary" id="reviewSubmit">${approving?'Approve & Schedule':'Return Request'}</button></div></div></div>`;
  document.body.appendChild(wrap);
  $('#review-feedback-choice').onchange=()=>$('#review-custom-wrap').style.display=$('#review-feedback-choice').value==='__custom__'?'':'none';
  $('#reviewSubmit').onclick=async()=>{
    try{const choice=$('#review-feedback-choice').value;const feedback=choice==='__custom__'?$('#review-custom').value.trim():choice;if(!feedback)throw new Error('Choose or enter feedback before submitting the decision.');await api(`/api/defense-requests/${id}/review`,{method:'PATCH',body:JSON.stringify({status:approving?'Approved':'Returned',feedback})});wrap.remove();toast(approving?'Request approved and scheduled automatically.':'Request returned with feedback.');renderView(state.view);}catch(err){toast(err.message)}};
}

function confirmModal(title,text,yesText,action){const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.id='modalConfirm';wrap.innerHTML=`<div class="modal"><div class="confirm-box"><div class="confirm-icon">✓</div><h4>${esc(title)}</h4><p>${esc(text)}</p><div class="modal-actions"><button class="btn" data-close-confirm>Cancel</button><button class="btn primary" data-confirm-action="${action}">${esc(yesText)}</button></div></div></div>`;document.body.appendChild(wrap)}

async function showReport(kind){try{const d=await api('/api/reports/'+kind);const rows=d.rows||[];const names={"defense-schedule":'Defense Schedule Report',"panel-assignment":'Panel Assignment Report',"student-status":'Student Status Report',evaluation:'Evaluation Report'};const keys=rows.length?Object.keys(rows[0]):[];$('#reportResult').innerHTML=`<div class="panel-head"><div><h3>${names[kind]||'Report'}</h3><span>${rows.length} record${rows.length===1?'':'s'}</span></div><button class="btn" data-report-export="${kind}">Export CSV</button></div><div class="panel-body table-wrap"><table class="data-table"><thead><tr>${keys.map(k=>`<th>${esc(k.replaceAll('_',' '))}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${keys.map(k=>`<td>${esc(r[k]??'—')}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${Math.max(1,keys.length)}"><div class="empty">No data available.</div></td></tr>`}</tbody></table></div>`;}catch(e){toast(e.message)}}
function exportRows(rows,filename){if(!rows.length){toast('No report data to export.');return;}const keys=Object.keys(rows[0]);const csv=[keys,...rows.map(r=>keys.map(k=>r[k]??''))].map(row=>row.map(x=>`"${String(x).replaceAll('\"','\"\"')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=filename;a.click();URL.revokeObjectURL(a.href)}
async function exportSummary(){const kinds=['defense-schedule','panel-assignment','student-status','evaluation'];for(const k of kinds){const d=await api('/api/reports/'+k);exportRows(d.rows||[],`report-${k}.csv`)}toast('Reports exported.')}

// Role selection and login flow
const ROLE_ACCESS = {
  student: { purpose:'STUDENT ACCESS', title:'MANAGE YOUR DEFENSE', tagline:'Submit defense requests, view your schedule, and check your recorded result.' },
  adviser: { purpose:'ADVISER ACCESS', title:'MONITOR YOUR PROJECT', tagline:'View assigned students, track project status, and provide evaluation/comments when assigned.' },
  panel_member: { purpose:'PANEL MEMBER ACCESS', title:'EVALUATE ASSIGNED DEFENSES', tagline:'View only assigned defenses, submit evaluations, and add comments or recommendations.' },
  coordinator: { purpose:'COORDINATOR ACCESS', title:'MANAGE DEFENSE OPERATIONS', tagline:'Manage users, projects, schedules, rooms, panel assignments, conflicts, and reports.' }
};
function applyLoginRoleCopy(role){
  const copy=ROLE_ACCESS[role]||ROLE_ACCESS.student;
  $('#loginRolePurpose').textContent=copy.purpose;
  $('#loginAccessTitle').textContent=copy.title;
  $('#loginAccessTagline').textContent=copy.tagline;
}
$$('.hero-role').forEach(btn=>btn.addEventListener('click',()=>{state.role=btn.dataset.role;applyRoleTheme(state.role);applyLoginRoleCopy(state.role);$$('.hero-role').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');$('#roleStep').classList.remove('active');$('#loginStep').classList.add('active');$('#loginRole').value=state.role;$('#selectedRole').textContent=roleLabel(state.role)}));
$('#changeRole').addEventListener('click',()=>{$('#loginStep').classList.remove('active');$('#roleStep').classList.add('active')});
$('#togglePassword').addEventListener('click',()=>{const p=$('#password');p.type=p.type==='password'?'text':'password';$('#togglePassword').textContent=p.type==='password'?'Show':'Hide'});
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();try{const d=await api('/api/login',{method:'POST',body:JSON.stringify({email:$('#email').value,password:$('#password').value,role:$('#loginRole').value})});state.user=d.user;state.role=d.user.role;csrfToken=d.csrfToken||csrfToken;showApp();toast(`Welcome, ${state.user.full_name.split(' ')[0]}.`)}catch(err){toast(err.message)}});

const heroMenuToggle=$('#heroMenuToggle'), heroMobileMenu=$('#heroMobileMenu');
function setHeroMenu(open){if(!heroMenuToggle||!heroMobileMenu)return;heroMenuToggle.classList.toggle('is-open',open);heroMenuToggle.setAttribute('aria-expanded',String(open));heroMenuToggle.setAttribute('aria-label',open?'Close menu':'Open menu');heroMobileMenu.classList.toggle('is-open',open);heroMobileMenu.setAttribute('aria-hidden',String(!open));if(open){heroMobileMenu.removeAttribute('inert');document.body.classList.add('menu-open');}else{heroMobileMenu.setAttribute('inert','');document.body.classList.remove('menu-open');}}
heroMenuToggle?.addEventListener('click',()=>setHeroMenu(!heroMenuToggle.classList.contains('is-open')));
heroMobileMenu?.addEventListener('click',e=>{if(e.target===heroMobileMenu)setHeroMenu(false); if(e.target.closest('a'))setHeroMenu(false);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&heroMenuToggle?.classList.contains('is-open')){setHeroMenu(false);heroMenuToggle.focus();}});
window.addEventListener('resize',()=>{if(window.innerWidth>900)setHeroMenu(false);});

// App actions
document.addEventListener('click',async e=>{
  const view=e.target.closest('[data-view]')?.dataset.view;if(view){if(window.innerWidth<=1080){$('#sidebar').classList.remove('open');$('#scrim').classList.remove('show')}return renderView(view)}
  if(e.target.closest('[data-modal]'))return openModal(e.target.closest('[data-modal]').dataset.modal);
  if(e.target.closest('[data-close-modal]'))return $('#modal')?.remove();
  if(e.target.closest('[data-close-confirm]'))return $('#modalConfirm')?.remove();
  if(e.target.closest('[data-close-profile]'))return $('#profileModal')?.remove();
  if(e.target.closest('[data-close-review]'))return $('#reviewModal')?.remove();
  if(e.target.closest('[data-close-room-assign]'))return $('#roomAssignModal')?.remove();
  if(e.target.closest('[data-close-user-edit]'))return $('#userEditModal')?.remove();
  const scheduleEdit=e.target.closest('[data-schedule-edit]');if(scheduleEdit){openScheduleEdit(scheduleEdit.dataset.scheduleEdit);return;}
  const panelDelete=e.target.closest('[data-panel-delete]');if(panelDelete){confirmModal('Remove panel assignment?','The person will be unassigned from this defense.','Remove',`panelDelete:${panelDelete.dataset.panelDelete}`);return;}
  const roomEdit=e.target.closest('[data-room-edit]');if(roomEdit){openRoomEdit(roomEdit.dataset.roomEdit);return;}
  const roomDelete=e.target.closest('[data-room-delete]');if(roomDelete){confirmModal('Delete this room?','Rooms assigned to active defenses cannot be deleted.','Delete',`roomDelete:${roomDelete.dataset.roomDelete}`);return;}
  const reqResubmit=e.target.closest('[data-resubmit-request]');if(reqResubmit){openResubmitRequest(Number(reqResubmit.dataset.resubmitRequest));return;}
  const feedbackResubmit=e.target.closest('[data-feedback-resubmit]');if(feedbackResubmit){api(`/api/feedback/${feedbackResubmit.dataset.feedbackResubmit}/student-response`,{method:'PATCH'}).then(()=>{toast('Revision marked as resubmitted.');renderView('projects')}).catch(err=>toast(err.message));return;}
  const report=e.target.closest('[data-report]');if(report){showReport(report.dataset.report);return;}
  const reportExport=e.target.closest('[data-report-export]');if(reportExport){api('/api/reports/'+reportExport.dataset.reportExport).then(d=>exportRows(d.rows||[],`report-${reportExport.dataset.reportExport}.csv`)).catch(err=>toast(err.message));return;}
  const projectDelete=e.target.closest('[data-project-delete]');if(projectDelete){confirmModal('Remove this project?','This permanently removes the project and its linked defense requests, schedules, panel assignments, evaluations, and feedback.','Remove project',`deleteProject:${projectDelete.dataset.projectDelete}`);return;}
  const editUser=e.target.closest('[data-user-edit]');if(editUser){openUserEdit(editUser.dataset.userEdit);return}
  const deleteUser=e.target.closest('[data-user-delete]');if(deleteUser){confirmModal('Delete this account?','This permanently removes the user account and related assignments/evaluations. This action cannot be undone.','Delete',`deleteUser:${deleteUser.dataset.userDelete}`);return}
  if(e.target.closest('#profileButton'))return openProfile();
  if(e.target.closest('[data-submit-modal]'))return submitModal(e.target.closest('[data-submit-modal]').dataset.submitModal);
  if(e.target.closest('[data-action="logout"]')){await api('/api/logout',{method:'POST'});location.reload();return}
  const review=e.target.closest('[data-review]');if(review){openReviewModal(Number(review.dataset.review),review.dataset.reviewStatus==='approve');return}
  const proceed=e.target.closest('[data-proceed]');if(proceed){confirmModal('Proceed with defense?','Confirm that you will proceed with the assigned defense.','Proceed',`proceed:${proceed.dataset.proceed}`);return}
  const resch=e.target.closest('[data-reschedule]');if(resch){openReschedule(resch.dataset.reschedule);return}
  const roomAssign=e.target.closest('[data-room-assign]');if(roomAssign){openRoomAssign(Number(roomAssign.dataset.roomAssign));return}
  const cancel=e.target.closest('[data-cancel]');if(cancel){confirmModal('Cancel this schedule?','The schedule will be marked cancelled.','Cancel schedule',`cancel:${cancel.dataset.cancel}`);return}
  const user=e.target.closest('[data-user-toggle]');if(user){confirmModal(user.dataset.active==='true'?'Deactivate account?':'Activate account?','The account status will change immediately.','Confirm',`user:${user.dataset.userToggle}:${user.dataset.active!=='true'}`);return}
  const rs=e.target.closest('[data-resched-review]');if(rs){api(`/api/reschedule-requests/${rs.dataset.reschedReview}`,{method:'PATCH',body:JSON.stringify({status:rs.dataset.status})}).then(()=>{toast('Reschedule request updated.');renderView('schedules')}).catch(err=>toast(err.message));return}
  const fsat=e.target.closest('[data-feedback-satisfied]');if(fsat){api(`/api/feedback/${fsat.dataset.feedbackSatisfied}/satisfaction`,{method:'PATCH',body:JSON.stringify({status:'Satisfied'})}).then(()=>{toast('Feedback marked satisfied.');renderView('projects')}).catch(err=>toast(err.message));return}
  const clarify=e.target.closest('[data-clarify]');if(clarify){openClarify(clarify.dataset.clarify);return}
  if(e.target.closest('[data-export]'))return exportSummary();
  if(e.target.closest('[data-confirm-action]')){
    const action=e.target.closest('[data-confirm-action]').dataset.confirmAction;$('#modalConfirm')?.remove();
    try{
      const [kind,a,b]=action.split(':');
      if(kind==='proceed'){const result=await api(`/api/schedules/${a}/proceed`,{method:'POST'});toast('Defense marked to proceed.');await renderView('schedules');}
      if(kind==='cancel'){await api(`/api/schedules/${a}/cancel`,{method:'PATCH'});toast('Schedule cancelled.');renderView('schedules')}
      if(kind==='user'){await api(`/api/users/${a}/status`,{method:'PATCH',body:JSON.stringify({is_active:b==='true'})});toast('Account status updated.');renderView('users')}
      if(kind==='deleteUser'){await api(`/api/users/${a}`,{method:'DELETE'});toast('User account deleted.');renderView('users')}
      if(kind==='deleteProject'){await api(`/api/projects/${a}`,{method:'DELETE'});toast('Project removed.');renderView('projects')}
      if(kind==='panelDelete'){await api(`/api/panels/${a}`,{method:'DELETE'});toast('Panel assignment removed.');renderView('panels')}
      if(kind==='roomDelete'){await api(`/api/rooms/${a}`,{method:'DELETE'});toast('Room deleted.');renderView('rooms')}
    }catch(err){toast(err.message)}
  }
});
document.addEventListener('change',async e=>{
  const panelRole=e.target.closest('#f-panel-role');if(panelRole){const scheduleId=Number($('#f-schedule')?.value);if(scheduleId){const [sd,opts]=await Promise.all([api('/api/schedules'),api('/api/panel-options')]);const schedule=(sd.schedules||[]).find(x=>Number(x.id)===scheduleId);renderPanelMemberOptions(schedule,opts);}}
  const ps=e.target.closest('[data-project-status]');if(ps){try{await api(`/api/projects/${ps.dataset.projectStatus}/status`,{method:'PATCH',body:JSON.stringify({status:ps.value})});toast('Project status updated.');renderView('projects')}catch(err){toast(err.message)}}
  const room=e.target.closest('[data-room]');if(room){try{await api(`/api/rooms/${room.dataset.room}`,{method:'PATCH',body:JSON.stringify({is_available:room.checked})});toast('Room availability updated.')}catch(err){toast(err.message)}}
  if(e.target.matches('#f-schedule-date,#f-schedule-start,#f-schedule-end')){refreshScheduleRooms().catch(err=>toast(err.message));}
  const week=e.target.closest('[data-week-status]');if(week){const progress=week.value==='Completed'?100:week.value==='In Progress'?50:week.value==='At Risk'?25:0;try{await api(`/api/weekly/${week.dataset.weekStatus}`,{method:'PATCH',body:JSON.stringify({status:week.value,progress})});toast('Weekly tracker updated.');renderView('management')}catch(err){toast(err.message)}}
});
async function openRoomEdit(id){const d=await api('/api/rooms');const r=d.rooms.find(x=>Number(x.id)===Number(id));if(!r)return toast('Room not found.');const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.id='modal';wrap.innerHTML=`<div class="modal"><div class="modal-head"><h3>Edit room</h3><button class="modal-close" data-close-modal>×</button></div><div class="modal-form"><label>Room name<input id="re-name" value="${esc(r.name)}"></label><label class="full">Location<input id="re-location" value="${esc(r.location)}"></label><div class="modal-actions"><button class="btn" data-close-modal>Cancel</button><button class="btn primary" id="saveRoomEdit">Save</button></div></div></div>`;document.body.appendChild(wrap);$('#saveRoomEdit').onclick=async()=>{try{await api('/api/rooms/'+id,{method:'PATCH',body:JSON.stringify({name:$('#re-name').value,location:$('#re-location').value})});wrap.remove();toast('Room updated.');renderView('rooms')}catch(e){toast(e.message)}};}
async function openRoomAssign(scheduleId){
  const [sd,rd]=await Promise.all([api('/api/schedules'),api('/api/rooms')]);
  const schedule=(sd.schedules||[]).find(x=>Number(x.id)===Number(scheduleId));if(!schedule)return toast('Schedule not found.');
  const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.id='roomAssignModal';
  const date=String(schedule.defense_date).slice(0,10),start=String(schedule.start_time).slice(0,5),end=String(schedule.end_time).slice(0,5);
  const slotRooms=await api(`/api/rooms?date=${encodeURIComponent(date)}&start=${encodeURIComponent(start)}&end=${encodeURIComponent(end)}&exclude_id=${encodeURIComponent(scheduleId)}`);
  const rooms=slotRooms.rooms||rd.rooms||[];
  wrap.innerHTML=`<div class="modal"><div class="modal-head"><div><p class="micro">DEFENSE SCHEDULE</p><h3>Assign room</h3></div><button class="modal-close" data-close-room-assign>×</button></div><div class="modal-form"><div class="full notice"><b>${esc(schedule.title)}</b><br>${dateFmt(schedule.defense_date)} · ${timeFmt(schedule.start_time)}–${timeFmt(schedule.end_time)}</div><label class="full">Room<select id="ra-room"><option value="">No room assigned</option>${rooms.filter(r=>r.is_available||Number(r.id)===Number(schedule.room_id)).map(r=>`<option value="${r.id}" ${Number(r.id)===Number(schedule.room_id)?'selected':''} ${r.occupied&&Number(r.id)!==Number(schedule.room_id)?'disabled':''}>${esc(r.name)} · ${esc(r.location)}${r.occupied&&Number(r.id)!==Number(schedule.room_id)?' · Occupied':''}</option>`).join('')}</select></label><div class="full muted">Rooms occupied by another defense during this date and time are unavailable.</div><div class="modal-actions"><button class="btn" data-close-room-assign>Cancel</button><button class="btn primary" id="saveRoomAssign">Save room</button></div></div></div>`;
  document.body.appendChild(wrap);
  $('#saveRoomAssign').onclick=async()=>{try{await api(`/api/schedules/${scheduleId}/room`,{method:'PATCH',body:JSON.stringify({room_id:Number($('#ra-room').value)||null})});wrap.remove();toast('Room assignment updated.');renderView('schedules')}catch(err){toast(err.message)}};
}

async function openReschedule(scheduleId){const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.id='modalReschedule';wrap.innerHTML=`<div class="modal"><div class="modal-head"><h3>Request reschedule</h3><button class="modal-close" data-close-reschedule>×</button></div><div class="modal-form"><label>Preferred date<input id="r-date" type="date"></label><label>Preferred time<input id="r-time" type="time"></label><label class="full">Reason<textarea id="r-reason" placeholder="Explain why the defense cannot proceed at the scheduled time."></textarea></label><div class="modal-actions"><button class="btn" data-close-reschedule>Cancel</button><button class="btn primary" id="rescheduleSend">Submit request</button></div></div></div>`;document.body.appendChild(wrap);$('#rescheduleSend').onclick=async()=>{try{await api('/api/reschedule-requests',{method:'POST',body:JSON.stringify({schedule_id:Number(scheduleId),preferred_date:$('#r-date').value,preferred_time:$('#r-time').value,reason:$('#r-reason').value})});toast('Reschedule request submitted.');wrap.remove();renderView('schedules')}catch(err){toast(err.message)}}}
function openClarify(scheduleId){const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.id='modalClarify';wrap.innerHTML=`<div class="modal"><div class="modal-head"><h3>Result clarification</h3><button class="modal-close" data-close-clarify>×</button></div><div class="modal-form"><label class="full">Message<textarea id="c-message" placeholder="Describe what you would like clarified about the recorded result."></textarea></label><div class="modal-actions"><button class="btn" data-close-clarify>Cancel</button><button class="btn primary" id="clarifySend">Send to adviser</button></div></div></div>`;document.body.appendChild(wrap);$('#clarifySend').onclick=async()=>{try{await api('/api/result-clarifications',{method:'POST',body:JSON.stringify({schedule_id:Number(scheduleId),message:$('#c-message').value})});toast('Clarification request sent.');wrap.remove()}catch(err){toast(err.message)}}}
function applyTheme(mode){
  const dark=mode==='dark';
  document.body.classList.toggle('dark-mode',dark);
  const t=$('#themeToggle');
  if(t){t.setAttribute('aria-label',dark?'Switch to light theme':'Switch to dark theme');t.innerHTML=`<span class="theme-toggle-icon">${dark?'☀':'☾'}</span><span class="theme-toggle-label">${dark?'Light':'Dark'}</span>`;}
  $('#authThemeLight')?.classList.toggle('is-active',!dark);
  $('#authThemeDark')?.classList.toggle('is-active',dark);
  localStorage.setItem('defense-theme',dark?'dark':'light');
}

applyTheme(localStorage.getItem('defense-theme')||'dark');
$('#themeToggle')?.addEventListener('click',()=>applyTheme(document.body.classList.contains('dark-mode')?'light':'dark'));
$('#authThemeLight')?.addEventListener('click',()=>applyTheme('light'));
$('#authThemeDark')?.addEventListener('click',()=>applyTheme('dark'));

$('#openSidebar').addEventListener('click',()=>{$('#sidebar').classList.add('open');$('#scrim').classList.add('show')});$('#closeSidebar').addEventListener('click',()=>{$('#sidebar').classList.remove('open');$('#scrim').classList.remove('show')});$('#scrim').addEventListener('click',()=>{$('#sidebar').classList.remove('open');$('#scrim').classList.remove('show')});

(async function bootstrap(){try{const c=await fetch('/api/csrf');const cd=await c.json().catch(()=>({}));csrfToken=cd.token||'';const s=await api('/api/session');if(s.user){state.user=s.user;state.role=s.user.role;showApp()}}catch{}})();
